### ISSUE TITLE
代码里有一处classFileList.addAll可能会添加一个内容会是个目录

### ISSUE THREAD

**Issue by rootphantomer** [0xrumble/BytecodeScreen#3]
https://github.com/0xrumble/BytecodeScreen/blob/f5e753ee920ae09e5afa0de461fd913c189a248a/src/main/java/app/MainScreen.java#L642

如果-j "./jar/jarfile/"   第一处的classFileList会新增的是一个目录。

此处代码应该可以注释掉。

**Comment by 0xrumble** [comment]
> https://github.com/0xrumble/BytecodeScreen/blob/f5e753ee920ae09e5afa0de461fd913c189a248a/src/main/java/app/MainScreen.java#L642
> 
> 如果-j "./jar/jarfile/" 第一处的classFileList会新增的是一个目录。
> 
> 此处代码应该可以注释掉。

这部分代码是为了递归读取文件夹下的class文件（以及文件夹下jar文件【这个由是否存在参数决定】），该代码逻辑下没有创建文件的代码，我试用windows10测试并没有这个情况

**Comment by rootphantomer** [comment]
> > https://github.com/0xrumble/BytecodeScreen/blob/f5e753ee920ae09e5afa0de461fd913c189a248a/src/main/java/app/MainScreen.java#L642
> > 
> > 如果-j "./jar/jarfile/" 第一处的classFileList会新增的是一个目录。
> > 此处代码应该可以注释掉。
> 
> 这部分代码是为了递归读取文件夹下的class文件（以及文件夹下jar文件【这个由是否存在参数决定】），该代码逻辑下没有创建文件的代码，我试用windows10测试并没有这个情况

ok，我理解了这层意思了。

我发现，当我
```bash
java -jar xxx.jar -m "{(set*)}" -p "{(java.lang.String)}" -r "{(void)}" -s java.awt.Component -j "/Users/ph4nt0mer/.m2/repository/org/apache/xmlgraphics/batik-swing/" --debug
```

跑org/apache/batik/swing/JSVGCanvas$setURI这个利用点的时候，发现不加--debug，没有result，加了--debug发现
![image](https://user-images.githubusercontent.com/6481352/198495681-6fb8f253-cceb-4ad9-98a2-880ea0d5b335.png)
但是result在下面这三处判断把resultclass给clear了，导致没result结果输出 https://github.com/0xrumble/BytecodeScreen/blob/f5e753ee920ae09e5afa0de461fd913c189a248a/src/main/java/app/MainScreen.java#L128

```java
 if (command.interfaces != null && hasinterfaces.isEmpty()) {
                    resultclass.clear();
                }
                if (command.superclass != null && hassuperclass.isEmpty()) {
                    resultclass.clear();
                }
                if (has_parameter.isEmpty()) {
                    resultclass.clear();
                }
```
command.superclass != null && hassuperclass.isEmpty()  为两个true
![image](https://user-images.githubusercontent.com/6481352/198495871-127a3c9e-9c55-40be-bd22-c234b4733f90.png)

**Comment by 0xrumble** [comment]
> 

我看了下你的问题，首先你的父类是在（C:\Program Files\Java\jdk1.8.0_71\jre\lib\rt.jar!\java\awt\Component.class)我的本地路径下
![image](https://user-images.githubusercontent.com/115286245/198530088-ecaf209a-f3e3-4e57-903b-8c9372ec89db.png)
你的使用语法中并没有包含本地rt.jar文件
`java -jar xxx.jar -m "{(set*)}" -p "{(java.lang.String)}" -r "{(void)}" -s java.awt.Component -j "/Users/ph4nt0mer/.m2/repository/org/apache/xmlgraphics/batik-swing/" --debug`
所以这时候工具扫描的targetclass中没有你所要继承的类文件，自然也就无法扫描。
这时候的解决方法有2种：
1.使用txt的方式解析目标，加上rt.jar文件的路径或java路径
2.使用--jar参数，让你的扫描默认加上rt.jar文件
这是我的参数以及结果
`-m "{(set*)}" -p "{(java.lang.String)}" -r "{(void)}" -s java.awt.Component -j "C:\Users\ThreatBook\.m2\repository\org\apache\xmlgraphics\batik-swing\1.7\batik-swing-1.7.jar"  --jar`
![image](https://user-images.githubusercontent.com/115286245/198531434-b148d97d-d1e6-4cd4-9f57-4cac5e119e0e.png)

**Comment by rootphantomer** [comment]
ok，了解。

**Comment by 0xrumble** [comment]
> ok，了解。

我有时间改下Readme，可能很多细节没有介绍清楚,谢谢
